# BÁO CÁO BÀI TẬP THỰC HÀNH VÀ ĐỒ ÁN CUỐI KỲ

- Dành cho lớp CS114.O21 và CS114.O21.KHCL

## THÔNG TIN NHÓM

- Mỗi SV của nhóm điền các thông tin như bên dưới

1. MSSV-1
  - Họ và Tên:
  - Số buổi vắng:
  - Số bài tập quá trình:
  - Điểm WeCode:

2. MSSV-2
  - Họ và Tên:
  - Số buổi vắng:
  - Số bài tập quá trình:
  - Điểm WeCode:


## THÔNG TIN ĐỒ ÁN - THỰC HÀNH

Các SV cần mô tả đầy đủ, càng chi tiết càng tốt về các bài thực hành đã làm để có cơ sở tính điểm đồ án và thực hành.

1. Trang github của nhóm (đặt tên repos là mã lớp học-MSSV, ví dụ CS114.O21-MSSV):

2. Đồ án cuối kỳ: MotocycleClassification
- Tổng số lượng ảnh đóng góp: xxx (ví dụ điền 50 - số này phải khớp với số mà hệ thống tự động tính). Nêu rõ phương pháp thu thập ảnh - và cách làm sạch dữ liệu ảnh. Post một số hình ảnh của các loại ở đây.
- Phương pháp rút trích đặc trưng sử dụng: xxx (ví dụ điền MobileNetV2)
- Thuật toán học được sử dụng: xxx (ví dụ điền LogisticRegression)
- Framework, thư viện sử dụng: xxx (ví dụ điền Keras, PyTorch, Tensorflow, Scikit-learn)
- Kết quả Accuracy: xxx (ví dụ điền 79.25%). Xếp hạng: 15 (theo danh sách file CS114.O21-O21.KHCL.ScoreBoard.csv)

3. Danh sách các bài thực hành đã làm - điền thời điểm (ngày, giờ) nộp bài trên Classroom:
- Thống kê dữ liệu (CS114.Tool.DatasetStat.ipynb): 2:40 AM, Jun 08
- Tạo các splits (CS114.Tool.CreateSplit.ipynb): None
- Hiển thị các ảnh (CS114.Tool.DatasetViz.ipynb):
- Ứng dụng Clustering (CS114.Clustering.ipynb):
- Đánh giá Model (CS114.Evaluation.ipynb):

4. Bài tập - Dự đoán điểm IT001
- Mô tả về đặc trưng, các code đã dùng để rút trích đặc trưng, kết quả rút trích lưu trữ quản lý thế nào?
- Thuật toán học, quá trình huấn luyện và thử nghiệm?

5. Bài tập - Nhận dạng chữ số viết tay
- Mô tả về dữ liệu đóng góp
- Mô tả về đặc trưng và thuật toán học

In [7]:
# from google.colab import drive
# drive.mount('/content/drive')

## MÔ TẢ HỖ TRỢ CỦA CÁC CÔNG CỤ NHƯ CHATGPT, GEMINI, POE

- Các SV mô tả vắn tắt việc dùng các công cụ để hỗ trợ cho việc thực hiện bài thực hành

## CODE CỦA ĐỒ ÁN MOTOCYCLECLASSIFICATION

1. Tham khảo các bước
  - https://keras.io/examples/vision/image_classification_from_scratch/

2. Các lưu ý:
  - Cần ghi rõ thông tin ngày cập nhật
  - Đoạn code của người khác nếu sử dụng lại, phải ghi tham chiếu để phân biệt đâu là code của mình, đâu là code của người khác
  - Cần phải có chú thích càng chi tiết càng tốt để code dễ đọc, dễ kiểm tra
  - Notebook nộp bài phải là notebook đã chạy và giữ lại output
  - Các hành vi gian lận sẽ bị trừng phạt rất nghiêm khắc

## CHIA DỮ LIỆU

### Tìm các ảnh lỗi và loại bỏ, sau đó lưu tập đường dẫn mới vào file csv mới

In [8]:
# def findInvalidPath(root_dir, path_list):
#     invalid_path = []
#     for path in path_list:
#         image_path = os.path.join(root_dir, path)
#         try:
#             with Image.open(image_path) as img:
#                 img.verify()
#         except (IOError, SyntaxError) as e:
#             invalid_path.append(path)
#     return invalid_path

In [9]:
# import os
# import pandas as pd
# # thư mục gốc chứa thư mục dữ liệu
# szWorkingDir = "./Data"
# for i in range(1, 6):
#     # Xác định split
#     curSplit = i
#     szTrainFileName = "MotocycleDataset-Splits-{}-Train.csv".format(curSplit)
#     szTestFileName = "MotocycleDataset-Splits-{}-Test.csv".format(curSplit)
#     train_image_dir = os.path.join(szWorkingDir, szTrainFileName)
#     test_image_dir = os.path.join(szWorkingDir, szTestFileName)
#     training_set = pd.read_csv(train_image_dir, header = None, names = ["path", "label"])
#     testing_set = pd.read_csv(test_image_dir, header = None, names = ["path", "label"])
#     invalid_path_train = findInvalidPath(szWorkingDir, training_set["path"].values)

#     # Loại Invalid path khỏi dataset
#     training_set = training_set[~training_set["path"].isin(invalid_path_train)]
#     training_set.reset_index()

#     # Ghi vào file csv
#     training_set.to_csv("./newsplits/MotocycleDataset-Split-{}-Train-New.csv".format(curSplit), index = False, header = None)

#     invalid_path_test = findInvalidPath(szWorkingDir, testing_set["path"].values)

#     # Loại Invalid path khỏi dataset
#     testing_set = testing_set[~testing_set["path"].isin(invalid_path_test)]
#     testing_set.reset_index()

#     # Ghi vào file csv
#     testing_set.to_csv("./newsplits/MotocycleDataset-Split-{}-Test-New.csv".format(curSplit), index = False, header = None)

# CODE CHẠY CHO MỘT SPLIT

- Các cells bên dưới sẽ phục vụ cho một split
- Trước mỗi Code cell, nên có Text cell để giải thích

## Import các thư viện & Khai báo các biến toàn cục

### Import các thư viện

In [10]:
import os
import numpy as np
import cv2 as cv
import pandas as pd
import csv
import matplotlib.pyplot as plt
import random

from PIL import Image, ImageFile

import tensorflow as tf
from tensorflow import keras
from tensorflow import data as tf_data
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, array_to_img, load_img
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import train_test_split

### Khai báo các biến toàn cục

In [11]:
# dùng để hiển thị
nNumImgsPerRow = 10
nImgHeight = nImgWidth = 150

# Xác định split
curSplit = 1
szTrainFileName = "MotocycleDataset-Splits-{}-Train.csv".format(curSplit)
szTestFileName = "MotocycleDataset-Splits-{}-Test.csv".format(curSplit)

### Khai báo các đường dẫn

In [12]:
# thư mục gốc chứa thư mục dữ liệu
# szWorkingDir = "/content/drive/MyDrive/Public"
# szFileNameDir = "/content/drive/MyDrive/MotorData"
# szWorkingDir = "./Data"
# szFileNameDir = "./newsplits"
szWorkingDir = "/kaggle/input/motocycledataset/Data"

In [13]:
# Đường dẫn tới file csv chưa path và label
train_image_path_csv = os.path.join(szWorkingDir, szTrainFileName)
test_image_path_csv = os.path.join(szWorkingDir, szTestFileName)

## Các hàm xử lý ảnh đầu vào

### Hàm kiểm tra ảnh

In [14]:
def findInvalidPath(root_dir, path_list):
    invalid_path = []
    for path in path_list:
        image_path = os.path.join(root_dir, path)
        try:
            with Image.open(image_path) as img:
                img.verify()
        except (IOError, SyntaxError, Exception) as e:
            print(f"Error loading image {image_path}: {e}")
            invalid_path.append(path)
    return invalid_path

## Bước 1 - Dataset Visualization

- Mục đích để kiểm tra xem dữ liệu có sạch, chuẩn hoá chưa

- Kết quả dự kiến <IMG SRC = 'https://editor.analyticsvidhya.com/uploads/762161_OSvbuPLy0PSM2nZ62SbtlQ.png'>

Chia dữ liệu theo lớp

In [15]:
# train_list = pd.read_csv(train_image_dir)
# train_list = np.array(train_list)
# Data = {0: [], 1: [], 2: [], 3: [], 4:[]}
# for train in train_list:
#   if train[1] == 0 and train[0] not in Data[0]:
#     Data[0].append(train[0])
#   elif train[1] == 1 and train[0] not in Data[1]:
#     Data[1].append(train[0])
#   elif train[1] == 2 and train[0] not in Data[2]:
#     Data[2].append(train[0])
#   elif train[1] == 3 and train[0] not in Data[3]:
#     Data[3].append(train[0])
#   else: Data[4].append(train[0])


In [16]:
# print(len(Data[0]), len(Data[1]), len(Data[2]), len(Data[3]), len(Data[4]))

Visualize

In [17]:
# fig, axes = plt.subplots(nrows = 5, ncols = 11, figsize = (20, 10))
# fig.suptitle('Dataset Visualization')
# for i in range(5):
#   image_paths = random.sample(Data[i], 10)
#   axes[i, 0].set_title (image_paths[0].split('.')[1])
#   axes[i, 0].axis("off")
#   for j, path in enumerate(image_paths):
#     img = cv.imread(os.path.join(szWorkingDir, path))
#     while img is None:
#       while path in image_paths:
#         path = random.sample(Data[i], 1)
#       img = cv.imread(os.path.join(szWorkingDir, path))
#     img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
#     axes[i, j+1].imshow(img)
#     axes[i, j+1].axis("off")

# plt.tight_layout()
# plt.show()


## Bước 2 - Data Augmentation

- Làm giàu dữ liệu bằng các công cụ có sẵn từ các framework như Keras
- Sử dụng `ImageDataGenerator`
- Có sự hỗ trợ của ChatGPT



In [18]:
batch_size = 64
seed = 42
width = 224
height = 224

In [19]:
train_paths = pd.read_csv(train_image_path_csv, header = None, names = ["path", "label"])
train_paths["label"] = train_paths["label"].astype(str)

invalid_paths = findInvalidPath(szWorkingDir, train_paths["path"].values)
train_paths = train_paths[~train_paths["path"].isin(invalid_paths)]
train_paths.reset_index()

Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1022.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1022.jpg'
Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1023.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1023.jpg'
Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1024.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1024.jpg'
Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1030.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520

index                                               path label
0          0  Honda/22520968-22520996-22520999-22520929-2252...     1
1          1  Honda/22520968-22520996-22520999-22520929-2252...     1
2          2  Honda/22520968-22520996-22520999-22520929-2252...     1
3          3  Honda/22520968-22520996-22520999-22520929-2252...     1
4          4  Honda/22520968-22520996-22520999-22520929-2252...     1
...      ...                                                ...   ...
27689  28037  Others/22520033-22520035-22520083-22520148-225...     0
27690  28038  Others/22520033-22520035-22520083-22520148-225...     0
27691  28039  Others/22520033-22520035-22520083-22520148-225...     0
27692  28040  Others/22520033-22520035-22520083-22520148-225...     0
27693  28041  Others/22520033-22520035-22520083-22520148-225...     0

[27694 rows x 3 columns]

In [20]:
#train_paths.to_csv(os.path.join(szFileNameDir, "MotocycleDataset-Splits-{}-Train-New.csv".format(curSplit)), index = False, header = None)

In [21]:
data_generator = ImageDataGenerator(
    rescale=1/255,
)

directory_config = {
    'dataframe': train_paths,
    'directory': szWorkingDir,
    'x_col': 'path',
    'y_col': 'label',
    'target_size': (height, width),
    'batch_size': batch_size,
    'class_mode': 'sparse',
    'shuffle': True,
    'seed': seed,
    'color_mode': 'rgb',
}

train_generator = data_generator.flow_from_dataframe(**directory_config, subset='training')


Found 27694 validated image filenames belonging to 5 classes.


In [22]:
train_generator

## Bước 3 - Feature Extraction

Load MobileNetV2 model pre-trained on ImageNet không bao gồm lớp đầu ra

In [23]:
base_model = MobileNetV2(weights='imagenet', include_top=False, pooling = 'avg', input_shape=(height, width, 3))
base_model.trainable = False

9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


Rút trích đặc trưng

In [24]:
def featuresFromMobileNetV2(generator, model):
  ImageFile.LOAD_TRUNCATED_IMAGES = True
  features = []
  labels = []
  num_samples = len(generator)

  for _ in range(num_samples):
      input_batch, label_batch = next(generator)
      features_batch = model.predict(input_batch)
      features.append(features_batch)
      labels.append(label_batch)

  return np.concatenate(features), np.concatenate(labels)

In [25]:
# # Trích xuất đặc trưng từ các ảnh
train_features, train_labels = featuresFromMobileNetV2(train_generator, base_model)

2/2 ━━━━━━━━━━━━━━━━━━━━ 9s 14ms/step


I0000 00:00:1719811340.194601     110 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


/opt/conda/lib/python3.10/site-packages/PIL/Image.py:992: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━

Label dang ở dạng OneHot vector nên ta cần làm phẳng mảng để đưa vào mô hình

In [26]:
train_labels

array([3., 2., 4., ..., 1., 4., 0.], dtype=float32)

Ghi vào csv cho trường hợp đổi model thì không phải rút trích đặc trưng lại

In [27]:
# np.save(os.path.join(szFileNameDir, "MotocycleDataset-Splits-{}-Train-Features.npy".format(curSplit)), train_features)
# np.save(os.path.join(szFileNameDir, "MotocycleDataset-Splits-{}-Train-Labels.npy".format(curSplit)), train_labels)

## Bước 4 - Model Configuration

- Có thể chọn Logistic Regression

In [28]:
# logistic = LogisticRegression(max_iter=1000, multi_class='auto', solver='lbfgs')

In [29]:
# Xây dựng mô hình CNN
ImageFile.LOAD_TRUNCATED_IMAGES = True
model = Sequential([
    Flatten(),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(5, activation='softmax')  # num_classes là số lượng lớp đầu ra
])

# Compile mô hình
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

## Bước 5 - Model Training

- Nên có visualize model accuracy, model loss để xem các hyperparameters có cần điều chỉnh không

In [30]:
# logistic.fit(train_features, train_labels)

In [60]:
# Huấn luyện mô hình
model.fit(train_features, train_labels, epochs=10, batch_size=128)

Epoch 1/10
 86/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9881 - loss: 0.0444

W0000 00:00:1719812225.743223     111 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


217/217 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9888 - loss: 0.0414
Epoch 2/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9929 - loss: 0.0250
Epoch 3/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9940 - loss: 0.0211
Epoch 4/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9931 - loss: 0.0245
Epoch 5/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9921 - loss: 0.0274
Epoch 6/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9940 - loss: 0.0225
Epoch 7/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9928 - loss: 0.0257
Epoch 8/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9925 - loss: 0.0284
Epoch 9/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9889 - loss: 0.0358
Epoch 10/10
217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9819 - loss: 0.0551


## Bước 6 - Model Evaluation

- Dùng model (kết quả của bước Model Training) để predict CategoryID của các ảnh trong tập dữ liệu Test, sau đó tính Accuracy và Confusion Matrix

In [32]:
test_paths = pd.read_csv(test_image_path_csv, header = None, names = ["path", "label"])
test_paths["label"] = test_paths["label"].astype(str)
invalid_test_paths = findInvalidPath(szWorkingDir, test_paths["path"].values)
test_paths = test_paths[~test_paths["path"].isin(invalid_test_paths)]

Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1027.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1027.jpg'
Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1098.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1098.jpg'
Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1116.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1116.jpg'
Error loading image /kaggle/input/motocycledataset/Data/Honda/22520968-22520996-22520999-22520929-22521373.Honda.1166.jpg: [Errno 2] No such file or directory: '/kaggle/input/motocycledataset/Data/Honda/22520

In [33]:

test_config = {
    'dataframe': test_paths,
    'directory': szWorkingDir,
    'x_col': 'path',
    'y_col': 'label',
    'target_size': (height, width),
    'batch_size': batch_size,
    'class_mode': 'sparse',
    'seed': seed,
    'shuffle': False,
    'color_mode': 'rgb',
}
test_generator = data_generator.flow_from_dataframe(**test_config)

Found 6929 validated image filenames belonging to 5 classes.


In [34]:
test_features, test_labels = featuresFromMobileNetV2(test_generator, base_model)
test_labels

# np.save(os.path.join(szFileNameDir, "MotocycleDataset-Splits-{}-Test-Features.npy".format(curSplit)), test_features)
# np.save(os.path.join(szFileNameDir, "MotocycleDataset-Splits-{}-Test-Labels.npy".format(curSplit)), test_labels)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


/opt/conda/lib/python3.10/site-packages/PIL/Image.py:992: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
2/2 ━━━━━━━━

array([1., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [35]:
test_features

array([[0.792628  , 0.53104895, 0.0680941 , ..., 0.        , 0.        ,
        0.42966327],
       [1.5791458 , 1.0999631 , 0.0126129 , ..., 0.6227345 , 0.2846938 ,
        0.22029199],
       [0.08987409, 1.5207266 , 0.        , ..., 0.08464038, 0.        ,
        0.34097186],
       ...,
       [0.3822252 , 1.5495667 , 0.04883216, ..., 0.13165371, 0.5042246 ,
        0.26358786],
       [0.23272288, 0.13765317, 0.06586426, ..., 0.        , 0.        ,
        1.197501  ],
       [0.3342326 , 1.7882136 , 0.60486907, ..., 0.00898378, 0.        ,
        0.4049937 ]], dtype=float32)

In [36]:
# predictions = logistic.predict(test_features)
# predictions

In [37]:
# print(classification_report(test_labels, predictions))

In [38]:
# from sklearn.metrics import accuracy_score
# acc = accuracy_score(test_labels, predictions)
# acc

In [39]:
# # Đánh giá mô hình
# test_loss, test_acc = model.evaluate(test_features)
# print('Test accuracy:', test_acc)

In [40]:
model.save("model_256_128.keras")

In [41]:
test_labels

array([1., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [43]:
type(test_labels)

numpy.ndarray

In [61]:
predictions = model.predict(test_features)

217/217 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [62]:
predictions

array([[3.4562335e-04, 8.3171809e-01, 1.6020155e-01, 7.7347411e-03,
        2.0371834e-08],
       [2.0875624e-01, 7.8175771e-01, 8.4407162e-03, 9.7519596e-04,
        7.0130925e-05],
       [2.7629701e-05, 9.9997234e-01, 7.9914271e-09, 4.0977116e-10,
        9.1723694e-14],
       ...,
       [9.9892873e-01, 8.9039517e-05, 4.1245375e-08, 6.9910026e-04,
        2.8308443e-04],
       [8.6418486e-01, 4.4872172e-02, 3.5339075e-03, 8.7409087e-02,
        4.0276895e-08],
       [9.9999988e-01, 6.4093668e-09, 3.7483343e-08, 1.1004492e-07,
        2.0809204e-16]], dtype=float32)

In [46]:
len(predictions)

6929

In [47]:
type(predictions)

numpy.ndarray

In [63]:
test_predictions = np.argmax(predictions, axis = 1)

In [49]:
type(test_predictions)

numpy.ndarray

In [64]:
test_predictions

array([1, 1, 1, ..., 0, 0, 0])

In [65]:
print(classification_report(test_labels, test_predictions))

              precision    recall  f1-score   support

         0.0       0.68      0.64      0.66      1311
         1.0       0.71      0.66      0.68      1917
         2.0       0.70      0.64      0.67      1297
         3.0       0.59      0.70      0.64      1640
         4.0       0.80      0.83      0.81       764

    accuracy                           0.68      6929
   macro avg       0.70      0.70      0.69      6929
weighted avg       0.69      0.68      0.68      6929



In [66]:
acc = accuracy_score(test_labels, test_predictions)
acc

0.6811949776302497

## Bước 7 - Submission

- Ghi kết quả ra tập tin CS114.O21-O21.KHCL.ScoreBoard.csv theo chế độ Append: https://drive.google.com/file/d/1qjGycdcIqsoag_yaVqY8UAUNmpFUkVFe/view?usp=sharing
- Quy ước:
  - Date: ví dụ 2024-06-11 10:32:19 (dùng hàm formatted_date = now.strftime("%Y-%m-%d %H:%M:%S"))
  - GroupID: các MSSV của thành viên trong nhóm cách nhau bằng dấu gạch ngang -, ví dụ 21522446-21522243
  - SplitID: giá trị từ 1 đến 5
  - Accuracy: giá trị theo quy ước dấu . phân cách phần thập phân, ví dụ 90.2345 - lấy đến 4 số thập phân
  - Desc: mô tả phương pháp, ví dụ Random. Mỗi nhóm có thể có rất nhiều trials, do đó cần phải mô tả tóm tắt về các trial để còn nhận diện
  


In [ ]:
from datetime import datetime
now = datetime.now()
Date = now.strftime("%Y-%m-%d %H:%M:%S")
GroupID = "22521705-22520777-22520202-22521304-22521716"
SplitID = "4"
Accuracy = round(acc*100, 4)
Accuracy = "{}".format(Accuracy)
Desc = "MobileNetV2 + Generators + CNN"
result = [Date, GroupID, SplitID, Accuracy, Desc]

In [ ]:
import csv
# with open("/content/drive/MyDrive/Public/CS114.O21-O21.KHCL.ScoreBoard.csv", mode='a', newline='') as file:
with open('result.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(result)

In [ ]:
df = pd.read_csv("/kaggle/working/result.csv")
df